### ISSUE TITLE
Spatie\DataTransferObject\DataTransferObjectError

### ISSUE THREAD

**Issue by interludic** [teamreflex/ChallongePHP#10]
I couldn't get this to work until i added

`
    public ?string $team_size_range;
    public ?string $toxic;
    public ?string $use_new_style;
    public array $optional_display_data;
`
to  vendor\team-reflex\challonge-php\src\Challonge\DTO\Tournament.php

Is it just me or does challonge not lock api versions?
I feel like this will break often in the future..

version 3.0.3

**Comment by xKairu** [comment]
Fixed with 3.0.4

I set the DTOs to ignore missing fields, so this shouldn't keep happening, with the caveat that new fields won't automatically be added to them. I have no idea how to test for some of these new fields either, so I'm just typing them based on what it sounds like they should be, eg: `use_new_style` sounds like a `bool`, but comes through as `NULL` for me, so `?bool` it is.
